/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module iiitb_r2_4bit_bm(clk, load, reset, M, Q, P);
  wire [3:0] _000_;
  wire [2:0] _001_;
  wire [3:0] _002_;
  wire [7:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire [3:0] A;
  wire [2:0] Count;
  input [3:0] M;
  wire [3:0] M_temp;
  output [7:0] P;
  input [3:0] Q;
  wire Q_minus_one;
  wire [3:0] Q_temp;
  input clk;
  input load;
  input reset;
  sky130_fd_sc_hd__clkinv_1 _223_ (
    .A(_122_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__clkinv_1 _224_ (
    .A(_116_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__clkinv_1 _225_ (
    .A(_117_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__clkinv_1 _226_ (
    .A(_118_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _227_ (
    .A(_120_),
    .B(_140_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__o21ai_0 _228_ (
    .A1(_122_),
    .A2(_121_),
    .B1(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nand2_1 _229_ (
    .A(_120_),
    .B(_140_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__a21oi_1 _230_ (
    .A1(_182_),
    .A2(_183_),
    .B1(_222_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21ai_0 _231_ (
    .A1(_120_),
    .A2(_140_),
    .B1(_121_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nor3_1 _232_ (
    .A(_120_),
    .B(_140_),
    .C(_121_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(_122_),
    .B(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a21oi_1 _234_ (
    .A1(_184_),
    .A2(_186_),
    .B1(_222_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o21bai_1 _235_ (
    .A1(_177_),
    .A2(_185_),
    .B1_N(_222_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__mux2i_1 _236_ (
    .A0(_127_),
    .A1(_123_),
    .S(_140_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nor2_1 _237_ (
    .A(_222_),
    .B(_187_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__mux2i_1 _238_ (
    .A0(_128_),
    .A1(_124_),
    .S(_140_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nor2_1 _239_ (
    .A(_222_),
    .B(_188_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__mux2i_1 _240_ (
    .A0(_129_),
    .A1(_125_),
    .S(_140_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(_222_),
    .B(_189_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__mux2i_1 _242_ (
    .A0(_130_),
    .A1(_126_),
    .S(_140_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor2_1 _243_ (
    .A(_222_),
    .B(_190_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor3_1 _244_ (
    .A(_122_),
    .B(_120_),
    .C(_121_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__or3_1 _245_ (
    .A(_122_),
    .B(_120_),
    .C(_121_),
    .X(_192_)
  );
  sky130_fd_sc_hd__and2_0 _246_ (
    .A(_137_),
    .B(_192_),
    .X(_193_)
  );
  sky130_fd_sc_hd__a211oi_1 _247_ (
    .A1(_136_),
    .A2(_191_),
    .B1(_193_),
    .C1(_140_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _248_ (
    .A(_140_),
    .SLEEP(_131_),
    .X(_195_)
  );
  sky130_fd_sc_hd__nor3_1 _249_ (
    .A(_222_),
    .B(_194_),
    .C(_195_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__and2_0 _250_ (
    .A(_138_),
    .B(_192_),
    .X(_196_)
  );
  sky130_fd_sc_hd__a211oi_1 _251_ (
    .A1(_137_),
    .A2(_191_),
    .B1(_196_),
    .C1(_140_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _252_ (
    .A(_140_),
    .SLEEP(_132_),
    .X(_198_)
  );
  sky130_fd_sc_hd__nor3_1 _253_ (
    .A(_222_),
    .B(_197_),
    .C(_198_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__and2_0 _254_ (
    .A(_139_),
    .B(_192_),
    .X(_199_)
  );
  sky130_fd_sc_hd__a211oi_1 _255_ (
    .A1(_138_),
    .A2(_191_),
    .B1(_199_),
    .C1(_140_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _256_ (
    .A(_140_),
    .SLEEP(_133_),
    .X(_201_)
  );
  sky130_fd_sc_hd__nor3_1 _257_ (
    .A(_222_),
    .B(_200_),
    .C(_201_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _258_ (
    .A(_136_),
    .SLEEP(_135_),
    .X(_202_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _259_ (
    .A(_135_),
    .SLEEP(_136_),
    .X(_203_)
  );
  sky130_fd_sc_hd__nor3_1 _260_ (
    .A(_191_),
    .B(_202_),
    .C(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__a21oi_1 _261_ (
    .A1(_127_),
    .A2(_116_),
    .B1(_191_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _262_ (
    .A(_127_),
    .SLEEP(_116_),
    .X(_206_)
  );
  sky130_fd_sc_hd__o21ai_0 _263_ (
    .A1(_127_),
    .A2(_116_),
    .B1(_205_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__a21oi_1 _264_ (
    .A1(_139_),
    .A2(_191_),
    .B1(_204_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__a22oi_1 _265_ (
    .A1(_178_),
    .A2(_204_),
    .B1(_207_),
    .B2(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nor2_1 _266_ (
    .A(_140_),
    .B(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _267_ (
    .A(_140_),
    .SLEEP(_134_),
    .X(_211_)
  );
  sky130_fd_sc_hd__nor3_1 _268_ (
    .A(_222_),
    .B(_210_),
    .C(_211_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _269_ (
    .A(_140_),
    .B(_191_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nor2_1 _270_ (
    .A(_135_),
    .B(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor3_1 _271_ (
    .A(_136_),
    .B(_140_),
    .C(_191_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nor3_1 _272_ (
    .A(_222_),
    .B(_213_),
    .C(_214_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__xor2_1 _273_ (
    .A(_128_),
    .B(_117_),
    .X(_215_)
  );
  sky130_fd_sc_hd__a21oi_1 _274_ (
    .A1(_127_),
    .A2(_116_),
    .B1(_215_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand2_1 _275_ (
    .A(_127_),
    .B(_215_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__and3_1 _276_ (
    .A(_127_),
    .B(_116_),
    .C(_215_),
    .X(_218_)
  );
  sky130_fd_sc_hd__and2_0 _277_ (
    .A(_192_),
    .B(_203_),
    .X(_219_)
  );
  sky130_fd_sc_hd__nand2_1 _278_ (
    .A(_192_),
    .B(_203_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nor3_1 _279_ (
    .A(_216_),
    .B(_218_),
    .C(_220_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _280_ (
    .A(_192_),
    .B(_202_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a31oi_1 _281_ (
    .A1(_192_),
    .A2(_202_),
    .A3(_217_),
    .B1(_116_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor3_1 _282_ (
    .A(_206_),
    .B(_215_),
    .C(_141_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor3_1 _283_ (
    .A(_219_),
    .B(_142_),
    .C(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o21bai_1 _284_ (
    .A1(_221_),
    .A2(_144_),
    .B1_N(_204_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _285_ (
    .A1(_117_),
    .A2(_204_),
    .B1(_140_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a221oi_1 _286_ (
    .A1(_140_),
    .A2(_178_),
    .B1(_145_),
    .B2(_146_),
    .C1(_222_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _287_ (
    .A(_129_),
    .B(_118_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__xor2_1 _288_ (
    .A(_129_),
    .B(_118_),
    .X(_148_)
  );
  sky130_fd_sc_hd__maj3_1 _289_ (
    .A(_128_),
    .B(_179_),
    .C(_206_),
    .X(_149_)
  );
  sky130_fd_sc_hd__xor2_1 _290_ (
    .A(_148_),
    .B(_149_),
    .X(_150_)
  );
  sky130_fd_sc_hd__a21oi_1 _291_ (
    .A1(_179_),
    .A2(_141_),
    .B1(_219_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o21ai_0 _292_ (
    .A1(_141_),
    .A2(_150_),
    .B1(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__and2_0 _293_ (
    .A(_128_),
    .B(_117_),
    .X(_153_)
  );
  sky130_fd_sc_hd__o21ai_0 _294_ (
    .A1(_218_),
    .A2(_153_),
    .B1(_148_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor3_1 _295_ (
    .A(_218_),
    .B(_148_),
    .C(_153_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nand2_1 _296_ (
    .A(_219_),
    .B(_154_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o21ai_0 _297_ (
    .A1(_155_),
    .A2(_156_),
    .B1(_152_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2b_1 _298_ (
    .A_N(_204_),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a21oi_1 _299_ (
    .A1(_118_),
    .A2(_204_),
    .B1(_140_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a221oi_1 _300_ (
    .A1(_140_),
    .A2(_179_),
    .B1(_158_),
    .B2(_159_),
    .C1(_222_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2b_1 _301_ (
    .A_N(_129_),
    .B(_118_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__o21a_1 _302_ (
    .A1(_148_),
    .A2(_149_),
    .B1(_160_),
    .X(_161_)
  );
  sky130_fd_sc_hd__xnor2_1 _303_ (
    .A(_130_),
    .B(_119_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__xor2_1 _304_ (
    .A(_130_),
    .B(_119_),
    .X(_163_)
  );
  sky130_fd_sc_hd__o211ai_1 _305_ (
    .A1(_148_),
    .A2(_149_),
    .B1(_160_),
    .C1(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__o2111ai_1 _306_ (
    .A1(_161_),
    .A2(_163_),
    .B1(_164_),
    .C1(_202_),
    .D1(_192_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(_118_),
    .B(_141_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a21oi_1 _308_ (
    .A1(_165_),
    .A2(_166_),
    .B1(_219_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__and3_1 _309_ (
    .A(_147_),
    .B(_154_),
    .C(_162_),
    .X(_168_)
  );
  sky130_fd_sc_hd__a21oi_1 _310_ (
    .A1(_147_),
    .A2(_154_),
    .B1(_162_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nor3_1 _311_ (
    .A(_220_),
    .B(_168_),
    .C(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__o21bai_1 _312_ (
    .A1(_167_),
    .A2(_170_),
    .B1_N(_204_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a21oi_1 _313_ (
    .A1(_119_),
    .A2(_204_),
    .B1(_140_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a221oi_1 _314_ (
    .A1(_140_),
    .A2(_180_),
    .B1(_171_),
    .B2(_172_),
    .C1(_222_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _315_ (
    .A(_119_),
    .B(_141_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a21oi_1 _316_ (
    .A1(_165_),
    .A2(_173_),
    .B1(_219_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor3_1 _317_ (
    .A(_140_),
    .B(_170_),
    .C(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _318_ (
    .A(_140_),
    .SLEEP(_119_),
    .X(_176_)
  );
  sky130_fd_sc_hd__nor3_1 _319_ (
    .A(_222_),
    .B(_175_),
    .C(_176_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__dfxtp_1 _320_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(A[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _321_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(A[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _322_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(A[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _323_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(A[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _324_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(P[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _325_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(P[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _326_ (
    .CLK(clk),
    .D(_003_[2]),
    .Q(P[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _327_ (
    .CLK(clk),
    .D(_003_[3]),
    .Q(P[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _328_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(P[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _329_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(P[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _330_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(P[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _331_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(P[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _332_ (
    .CLK(clk),
    .D(_002_[0]),
    .Q(M_temp[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _333_ (
    .CLK(clk),
    .D(_002_[1]),
    .Q(M_temp[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _334_ (
    .CLK(clk),
    .D(_002_[2]),
    .Q(M_temp[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _335_ (
    .CLK(clk),
    .D(_002_[3]),
    .Q(M_temp[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _336_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(Count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _337_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(Count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _338_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(Count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _339_ (
    .CLK(clk),
    .D(_004_),
    .Q(Q_minus_one)
  );
  sky130_fd_sc_hd__dfxtp_1 _340_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(Q_temp[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _341_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(Q_temp[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _342_ (
    .CLK(clk),
    .D(_003_[2]),
    .Q(Q_temp[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _343_ (
    .CLK(clk),
    .D(_003_[3]),
    .Q(Q_temp[3])
  );
  assign _003_[7:4] = _000_;
  assign _122_ = Count[2];
  assign _136_ = Q_temp[0];
  assign _135_ = Q_minus_one;
  assign _120_ = Count[0];
  assign _140_ = load;
  assign _222_ = reset;
  assign _001_[0] = _104_;
  assign _121_ = Count[1];
  assign _001_[1] = _105_;
  assign _001_[2] = _106_;
  assign _127_ = M_temp[0];
  assign _123_ = M[0];
  assign _002_[0] = _107_;
  assign _128_ = M_temp[1];
  assign _124_ = M[1];
  assign _002_[1] = _108_;
  assign _129_ = M_temp[2];
  assign _125_ = M[2];
  assign _002_[2] = _109_;
  assign _130_ = M_temp[3];
  assign _126_ = M[3];
  assign _002_[3] = _110_;
  assign _131_ = Q[0];
  assign _137_ = Q_temp[1];
  assign _003_[0] = _111_;
  assign _132_ = Q[1];
  assign _138_ = Q_temp[2];
  assign _003_[1] = _112_;
  assign _133_ = Q[2];
  assign _139_ = Q_temp[3];
  assign _003_[2] = _113_;
  assign _134_ = Q[3];
  assign _116_ = A[0];
  assign _003_[3] = _114_;
  assign _004_ = _115_;
  assign _117_ = A[1];
  assign _000_[0] = _100_;
  assign _118_ = A[2];
  assign _000_[1] = _101_;
  assign _119_ = A[3];
  assign _000_[2] = _102_;
  assign _000_[3] = _103_;
endmodule
